### ISSUE TITLE
snow_parking_intent should check validity of address

### ISSUE THREAD

**Issue by alidaniell** [codeforboston/voiceapp311#112] opened 2018-07-04 00:10 UTC
snow_parking_intent.py appears to not check validity of address input.  Could address be validated in get_snow_emergency_parking_intent function?

**Comment by jmartini** [comment] 2018-11-24 20:37
@alidaniell can you expand on this? What is does the user see that is incorrect? What are the reproduction steps?

**Comment by alidaniell** [comment] 2018-11-27 23:51
This is related to Issue #143, in which the Snow Parking intent allows the user to specify an address that does not exist in Boston, and then locates a parking lot that Alexa says is closest to the non-existing address.  The example given in Issue #143 was for 32 Miller Street.  

I think it would be better behavior for the Snow Parking intent to validate the address before trying to find the closest emergency snow parking, and if the address validation fails, Alexa should tell the user that she can't find the address in Boston and to please try again with another Boston address. If the user tries three bad ones in a row, Alexa should exit or let them choose to try another address.

Alexa

User:  Open Boston Info
Alexa: Welcome to the Boston Info skill. How can I help you?
User: snow emergency
Alexa: What's your address?
User: 32 miller St
Alexa: Sorry, I can't find that address in Boston. Please tell me another Boston address and I will find the closest snow emergency parking lot.
User:  i live at 500 mock fake lane
Alexa: Sorry, I can't find that address in Boston. Please tell me another Boston address and I will find the closest snow emergency parking lot.
User: I live at 300 Ancientbrady Drive
Alexa:  Sorry, I can't find that address in Boston. Say "try another address" if you want to keep looking.
User: [nothing]
[Alexa waits five seconds, and if no response, says the "How can I help you?" and waits for input on what skill the user wants]

If the user says try another address, Alexa continues asking for another address:
User: try another address
Alexa: What's your address?
User: 100 State Street
Alexa:  The closest snow emergency parking lot, Boston Common Garage, is at Zero Charles Street Boston, MA. It is 0.8 mi away and should take you 6 mins to drive there. The lot has 200 spaces when empty. The fee is $2 for each 24-hour period. The garage is for Beacon Hill, Back Bay, and Downtown residents only. You need to visit the garage office with proof of your residency to get the discount and park. Call 617-954-2098 for information.

**Comment by thiteixeira** [comment] 2019-03-23 15:16
Duplicate of #125 and #112 and #126

**Closed by thiteixeira** 2019-03-23 15:16 UTC
Labels: bug
