### ISSUE TITLE
Snow emergency intent accepts incorrect address, gives result for mystery address

### ISSUE THREAD

**Issue by alidaniell** [codeforboston/voiceapp311#143] opened 2018-08-15 00:54 UTC
Using address that doesn't exist in Boston, 32 Miller street, Snow Parking intent gives a parking lot for it.
Trying 32 Miller Street which doesn't exist in Boston: 

Response: "The closest snow emergency parking lot, Municipal Lot #013, is at 451-467 River St Boston, MA. It is 3.1 mi away and should take you 10 mins to drive there. The lot has 90 spaces when empty. There is no fee."

Trying 32 Mill Street, which does exist in Boston, gives different parking lot:

The closest snow emergency parking lot, Municipal Lot #020 , is at 191 Adams St Boston, MA. It is 0.9 mi away and should take you 5 mins to drive there. The lot has 22 spaces when empty. There is no fee.

It is not clear which address the snow emergency parking is using to provide its result in the case of an address that doesn't exist in Boston.
Do we want to do more checking for address validity for the Snow Emergency Parking intent?

**Comment by thiteixeira** [comment] 2019-02-12 18:05
Duplicate of #125

**Closed by thiteixeira** 2019-02-12 18:05 UTC
Labels: bug
