### ISSUE TITLE
Street Cleaning

### ISSUE THREAD

**Issue by Rizz311** [codeforboston/voiceapp311#34] opened 2018-01-10 01:25 UTC
Should be able to ask Alexa when the street cleaning is coming in my neighborhood

**Comment by Joshhw** [comment] 2018-01-17 02:21
is this any different from the other street sweeping issue we're doing?

**Comment by Rizz311** [comment] 2018-01-17 06:37
I'm sorry I got caught up at Resilient with a fellow that needed help I will be in next meet up on Tuesday

Sent from Yahoo Mail on Android 
 
  On Tue, Jan 16, 2018 at 9:21 PM, Joshua Decosta<notifications@github.com> wrote:   
is this any different from the other street sweeping issue we're doing?

**Comment by jmartini** [comment] 2018-02-14 00:58
Closing this as duplicate of #5

**Closed by jmartini** 2018-02-14 00:58 UTC
